In [20]:
replace = raw_input('Clusters have already been produced, replace? (y/n) ')
n_ent = 1
while(not(replace=='y' or replace == 'n')):
    
    replace = raw_input("Response not recognized. Replace existing clusters? (y/n): ")
    if n_ent == 10:
        print("Too many invalid responses. Exiting program.")
        break
    n_ent += 1    
print(replace)

Clusters have already been produced, replace? (y/n) 1
Response not recognized. Replace existing clusters? (y/n): 2
Response not recognized. Replace existing clusters? (y/n): 3
Response not recognized. Replace existing clusters? (y/n): 4
Response not recognized. Replace existing clusters? (y/n): 5
Response not recognized. Replace existing clusters? (y/n): 6
Response not recognized. Replace existing clusters? (y/n): 7
Response not recognized. Replace existing clusters? (y/n): 8
Response not recognized. Replace existing clusters? (y/n): 9
Response not recognized. Replace existing clusters? (y/n): 10
Response not recognized. Replace existing clusters? (y/n): 11
Too many invalid responses. Exiting program.
11


In [25]:

identifier = raw_input('Enter the identifier of the data or type \'help\' for clarification: ')
if identifier == 'help':
    n_help = 1
    while(identifier == 'help'):
        if n_help == 2:
            print("\'help\' will be the assigned ID.")
            break
        print(
        '''
        This will look for a numpy array (.npy) with the identifier as a prefix.
        If you haven\'t made the numpy array with keplerml.py, abort this with ctrl-c and run
        keplerml.py. If you have run keplerml.py, input the identifier you chose.
        
        If you would like to assign \'help\' as the ID, enter it again when prompted,
        this help text will not appear again.

        For example, if you chose \'ex\', there will be a .npy file 
        called exdataByLightCurve.npy that will be read in.
        For the identifier you would input \'ex\'
        ''')
        identifier = raw_input('Enter the identifier of the data: ')
        
        n_help += 1

Enter the identifier of the data or type 'help' for clarification: help

        This will look for a numpy array (.npy) with the identifier as a prefix.
        If you haven't made the numpy array with keplerml.py, abort this with ctrl-c and run
        keplerml.py. If you have run keplerml.py, input the identifier you chose.
        
        If you would like to assign 'help' as the ID, enter it again when prompted.

        For example, if you chose 'ex', there will be a .npy file 
        called exdataByLightCurve.npy that will be read in.
        For the identifier you would input 'ex'
        
Enter the identifier of the data: help
'help' will be the assigned ID.


In [3]:
import sys,os
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk
from tkFileDialog import askopenfilename

Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
filename = askopenfilename() # show an "Open" dialog box and return the path to the selected file
pathtofile = os.path.dirname(filename)
print(filename)
print(pathtofile)

/home/dgiles/Documents/NESSF.zip
/home/dgiles/Documents


In [18]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=4, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)

print(indices)
print(distances[:,3])

[[0 1 2 3]
 [1 0 2 3]
 [2 1 0 3]
 [3 4 5 0]
 [4 3 5 0]
 [5 4 3 0]]
[ 2.82842712  3.60555128  5.          2.82842712  3.60555128  5.        ]


In [4]:
# Random index selection
import numpy as np
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk
from tkFileDialog import askopenfilename

print('Select the filelist')
Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
filelist = askopenfilename() # show an "Open" dialog box and return the path to the selected file

files = [line.strip() for line in open(filelist)]

randomLCs = np.random.choice(files, 1000, replace=False)

# test if Tabby star is included in the otherwise random set, insert if not
import fnmatch

tabbyCheck = fnmatch.filter(randomLCs, '*8462852*')
tabby = fnmatch.filter(files,'*8462852*')

if tabbyCheck==[]:
    randomLCs = np.delete(randomLCs,0)
    randomLCs = np.insert(randomLCs,0,tabby)
# output random filelist to randomizedFilelist
for i in range(len(randomLCs)):
    outputfile = open('randomizedFilelist','w')
    outputfile.write('%s\n'%randomLCs[i]) 

[54 25 26 61  9]


In [20]:
import fnmatch

files = ['a','b','c','d','e','heyo8462852.pie','f','g','h','i']
randomLCs = np.random.choice(files, 3, replace=False)
print(randomLCs)

tabbyCheck = fnmatch.filter(randomLCs, '*8462852*')
tabby = fnmatch.filter(files,'*8462852*')

if tabbyCheck==[]:
    randomLCs = np.delete(randomLCs,0)
    randomLCs = np.insert(randomLCs,0,tabby)
    
print(randomLCs)

['h' 'i' 'g']
Not Present
['heyo8462852.pie' 'i' 'g']


In [24]:
from datetime import datetime,time,timedelta
import os
from multiprocessing import Pool

thentime = datetime(2016,9,1,11,15,38)
times = [datetime(2016,9,1,11,16,38),datetime(2016,9,1,11,16,50),datetime(2016,9,1,11,17,50)]
#timedelta(days,seconds,microseconds,milliseconds,minutes,hours,weeks)
diff = timedelta(minutes=1)
identifier = 'test'

timediff = nowtime-thentime

def timeDifference(time):
    timediff=time-thentime
    nfile = str(time)[14:19]
    if time == datetime(2016,9,1,11,17,50):
        # inducing an error
        timediff = 'cat'
    if timediff>=diff:
        kml_log = identifier+'_kml_log'
        os.system('echo %s ... %s >> %s'%(nfile,timediff,kml_log))
    return timediff

p = Pool(3)
timediffs = p.map(timeDifference,times)
p.close()
p.terminate()
p.join()

print(timediffs)

TypeError: can't compare datetime.timedelta to str

In [74]:
import numpy as np
f = [3,2,3,-1,-2,-3]
#os.system('echo %s >> testoutput'%f)
files = [line.strip()[:] for line in open('testoutput')]
files.sort()
f = open('testsortedoutput','w')
for line in files:
    f.write(line[5:]+'\n')
f.close()
npfiles = np.loadtxt('testsortedoutput',delimiter=',')

def printthing():
    print(npfiles)
printthing()

[[ 1.  2.  3. -1. -2. -3.]
 [ 3.  2.  3. -1. -2. -3.]
 [ 2.  2.  3. -1. -2. -3.]]


In [86]:
hi = "Hi there "
hi5='%s'*5%(hi,hi,hi,hi,hi)
bye5=hi5.replace('Hi',"Bye")
print(hi5)
print(bye5)

Hi there Hi there Hi there Hi there Hi there 
Bye there Bye there Bye there Bye there Bye there 


In [21]:
import numpy as np
import os

files = [cat.strip() for cat in open('test_kml_log')]

print open('test_kml_log').readline()

line2



In [9]:
import Tkinter, Tkconstants, tkFileDialog

class TkFileDialogExample(Tkinter.Frame):

  def __init__(self, root):

    Tkinter.Frame.__init__(self, root)

    # options for buttons
    button_opt = {'fill': Tkconstants.BOTH, 'padx': 5, 'pady': 5}

    # define buttons
    Tkinter.Button(self, text='Choose Filelist', command=self.askopenfilename).pack(**button_opt)
    Tkinter.Button(self, text='Choose Output', command=self.asksaveasfilename).pack(**button_opt)
    Tkinter.Button(self, text='Choose Fits Files Directory', command=self.askdirectory).pack(**button_opt)

    # define options for opening or saving a file
    self.file_opt = options = {}
    options['initialdir'] = 'C:\\'
    options['parent'] = root
    options['title'] = 'This is a title'

    # This is only available on the Macintosh, and only when Navigation Services are installed.
    #options['message'] = 'message'

    # if you use the multiple file version of the module functions this option is set automatically.
    #options['multiple'] = 1

    # defining options for opening a directory
    self.dir_opt = options = {}
    options['initialdir'] = 'C:\\'
    options['mustexist'] = False
    options['parent'] = root
    options['title'] = 'This is a title'

  def askopenfilename(self):

    """Returns an opened file in read mode.
    This time the dialog just returns a filename and the file is opened by your own code.
    """

    # get filename
    filename = tkFileDialog.askopenfilename(**self.file_opt)

    # open file on your own
    if filename:
      return open(filename, 'r')

  def asksaveasfilename(self):

    """Returns an opened file in write mode.
    This time the dialog just returns a filename and the file is opened by your own code.
    """

    # get filename
    filename = tkFileDialog.asksaveasfilename(**self.file_opt)

    # open file on your own
    if filename:
      return open(filename, 'w')

  def askdirectory(self):

    """Returns a selected directoryname."""

    return tkFileDialog.askdirectory(**self.dir_opt)

if __name__=='__main__':
  root = Tkinter.Tk()
  TkFileDialogExample(root).pack()
  root.mainloop()


KeyboardInterrupt: 

In [16]:
import numpy as np

data = ['1','2','3']
data1 = [4,5,6,7]
data2 = [8,9,10,11,12,13]
files_array = []
files_array = data+data1+data2
print(files_array)

['1', '2', '3', 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [30]:
import cPickle as pickle
import numpy as np
import os
from multiprocessing import Pool

"""
IMPORTANT NOTE: It's possible to dump multiple times to the same output file. Loading that data will only load one
dump at a time, so it must be loaded as many times as it's dumped to access all data in a file.
"""

array = ['cat',1,2,3,1.234]
array2 = ['dog',4,5,6,6.543]
array3 = ['fish',1,10,100,1000.0001]
allarrays=[array,array2,array3]
# testing pickling


def picklestuff(stuff):
    if not os.path.isfile('testoutput'):
        open('testoutput','a').close()
    output = open('testoutput','a')
    pickle.dump(stuff,output)
    output.close()

if not os.path.isfile('testoutput'):
        open('testoutput','a').close()
output = open('testoutput','r+')
pickle.dump(array2,output)
pickle.dump(array3,output)
pickle.dump(array,output)
output.close()

# testing unpickling
testinput = open('testoutput','r+')
"""
pik=pickle.load(testinput)
pik2=pickle.load(testinput)
testinput.close()
"""
pik=[]
while True:
    try:
        o = pickle.load(testinput)
    except EOFError:
        break
    else:
        pik.append(o)
testinput.close()

print(pik)
print('')
pik.sort()

# Testing if it all pickles as one array now.
output=open('testsortedoutput','r+')
pickle.dump(pik,output)
output.close()

testinput = open('testsortedoutput','r')
newpik = pickle.load(testinput)
testinput.close()
print(newpik)
# it does pickle as one array now, good.
animals = [newpik[i][0] for i in range(len(newpik))]
print(animals)

[['dog', 4, 5, 6, 6.543], ['fish', 1, 10, 100, 1000.0001], ['cat', 1, 2, 3, 1.234]]

[['cat', 1, 2, 3, 1.234], ['dog', 4, 5, 6, 6.543], ['fish', 1, 10, 100, 1000.0001]]
['cat', 'dog', 'fish']


In [1]:
import sys
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk

from tkFileDialog import askopenfilename,askdirectory


Tk().withdraw() 
output = askopenfilename()

if output:
    outputfile = open(output,'r+') # show an "Open" dialog box and return the path to the selected file
    print("woo")
    outputfile.close()
else:
    print("boo")



boo


In [3]:
import numpy as np
np.set_printoptions(threshold='nan')
import os
import sys
import cPickle as pickle
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk

from tkFileDialog import askopenfilename,askdirectory
output = askopenfilename() # locate the pickle file with the relevant data

if output:
    pathtofile = os.path.dirname(output)
    outputfile = open(output,'r+') # show an "Open" dialog box and return the path to the selected file
    outputdata = []
    while True:
        try:
            o = pickle.load(outputfile)
        except EOFError:
            break
        else:
            outputdata.append(o)
    outputfile.close()

    files = [outputdata[i][0] for i in range(len(outputdata))]
    data = np.array([outputdata[i][1:] for i in range(len(outputdata))])
    print(files[0])
    print(data[0])

In [41]:
#run cell above before this one
weirddata = [i for i in data if np.isnan(i).any()]
weirddatainds = [i for i in range(len(data)) if np.isnan(data[i]).any()]
print(weirddatainds)

[46863, 50739, 77707, 92257, 159088]


In [46]:
ind=4
print(files[weirddatainds[ind]])
print(weirddata[ind])

kplr011495654-2010174085026_llc.fits
[ -9.93052528e-04   9.84048903e-01  -2.68960282e-01   1.53136747e-02
   1.25754356e-01   1.23748437e-01   0.00000000e+00   0.00000000e+00
   0.00000000e+00   2.06300000e+03  -1.25817058e+00   1.10004127e-01
   1.80803572e-03   2.40955732e-02  -1.63906125e-02   1.13105677e-02
  -9.22863996e-03  -1.22559421e+00   1.00000000e+00   2.08192773e-03
   1.75979106e-01   3.62931098e-05   1.40091913e-04   1.03473570e-02
   1.48490393e-01   5.00000000e+00   9.00000000e+00   1.70000000e+01
   1.70000000e+01   1.52735526e+00   3.00000000e+00   1.05000000e+02
   2.00000000e+00   5.00000000e+00              nan   1.43846328e-04
   0.00000000e+00   0.00000000e+00   6.92923236e+01   4.33051726e-03
   8.66103452e-03   9.16041195e-01   3.79079232e-01   3.85223977e-01
   0.00000000e+00   1.72380316e-01   4.03968186e-01   6.27886671e-01
   8.24295422e-01   9.49554305e-01   1.55821562e-01   4.11052753e-01
   8.83818335e-01   9.99997513e-01   9.47999114e-04   4.55169903e-

In [11]:
import numpy as np
ints = [0,2,4]
otherints = [1,3,5]
array = np.array(['a','b','c','d','e','f'])
newarray = []
newarray.append(array[ints])
newarray.append(array[otherints])
print(newarray[0])
print(array[ints+otherints])

['a' 'c' 'e']
['a' 'c' 'e' 'b' 'd' 'f']


In [25]:
a = np.array([1,1,1,1,1,1,None,2,2,2,2,3,None])
a = [i for i in a if i !=None]
print(a)

[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3]


In [6]:
from datetime import datetime,time,timedelta
import random
import numpy as np
from multiprocessing import Pool,cpu_count
import sys
import os
import cPickle as pickle
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk
    
from tkFileDialog import askopenfilename,askdirectory

from numbapro import cuda

root = Tk.Tk()
root.wm_title("Scatter")

def reorganizeArray(X): 
    # This is just a transposition, could be accomplished by making X an np.array then transposing via X.T if prefered
    # TODO: Time the difference with large datasets (100,000+)
    return [[X[i][j] for i in range(len(X))] for j in range(len(X[0]))]

def clusterInds(i):
    clusterLabels=np.load('labels_temp.npy')
    if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels):
        return i

@cuda.autojit
def clusterIndsCuda(clusterLabels,clusterIndexes):
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
    if i<=len(clusterLabels):
        if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels):
            clusterIndexes[i]=i
        else:
            clusterIndexes[i]=None
    
    
Tk.Tk.withdraw(root)
print("Choose the directory the cluster data is contained in.")
pathtofile = askopenfilename() # Choose the cluster file
openclusterfile = open(pathtofile,'r+')
print("Importing pickle file...")
clusterfile = pickle.load(openclusterfile)
print("File imported")
openclusterfile.close()

clusterLabels = np.array(clusterfile[1])

print("Seperating into clusters, outliers, and centers...")

multiStart = datetime.now()
np.save('labels_temp.npy',clusterLabels)
numcpus = cpu_count()
usecpus = numcpus-2

p = Pool(usecpus)
clusterIndices = p.map(clusterInds,range(len(clusterLabels)))
p.close()
p.terminate()
p.join()
os.remove('labels_temp.npy')

multiEnd = datetime.now()

### Start Cuda GPU Stuff ###
d_clusterLabels = cuda.to_device(clusterLabels)
d_clusterIndexes=cuda.device_array_like(clusterLabels)
N=len(clusterLabels)
threads_per_block = 128
number_of_blocks =N/128+1

clusterIndsCuda [ number_of_blocks, threads_per_block ] (d_clusterLabels,d_clusterIndexes)

clusterIndexes = d_clusterIndexes.copy_to_host()

gpuEnd = datetime.now()
multiTime = multiEnd-multiStart
singleTime = gpuEnd-multiEnd

print("Multi processing took: %s"%multiTime)
print("Single processing took: %s"%singleTime)
print(clusterIndexes==clusterIndices)
"""print("Seperated, choosing random cluster points to display...")
# I don't think anyone has a real interest in seeing hundreds of thousands of 'normal' points, choosing a random sampling
# TODO: use density estimation to display all data
randomClusterIndices = np.random.choice(clusterIndices,1000,replace=False)
print("Reforming data arrays...")
inds = np.append(randomClusterIndices,outlierIndices)
inds = np.append(inds,centerIndices)
inds = [i for i in inds if i!=None]
files = files[inds]
clusterLabels = clusterLabels[inds]
data = data[inds]
plotArray = [files,clusterLabels,data]
print("Plot in next cell.")"""

Choose the directory the cluster data is contained in.
Importing pickle file...
File imported
Seperating into clusters, outliers, and centers...


TypingError: Caused By:
Traceback (most recent call last):
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 463, in stage_nopython_frontend
    self.locals)
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 780, in type_inference_stage
    infer.propagate()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 565, in propagate
    raise errors[0]
TypingError: Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-6-ffcac364267d>", line 37

Failed at nopython (nopython frontend)
Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-6-ffcac364267d>", line 37

In [8]:
from datetime import datetime,time,timedelta
import random
import numpy as np
from multiprocessing import Pool,cpu_count
import sys
import os
import cPickle as pickle
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk
    
from tkFileDialog import askopenfilename,askdirectory

from numbapro import cuda

@cuda.autojit
def clusterIndsCuda(clusterLabels,clusterIndexes):
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
    if i<=len(clusterLabels):
        if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels):
            clusterIndexes[i]=i
        else:
            clusterIndexes[i]=None

multiEnd = datetime.now()

### Start Cuda GPU Stuff ###
d_clusterLabels = cuda.to_device(clusterLabels)
d_clusterIndexes=cuda.device_array_like(clusterLabels)
N=len(clusterLabels)
threads_per_block = 128
number_of_blocks =N/128+1

clusterIndsCuda[number_of_blocks,threads_per_block ] (d_clusterLabels,d_clusterIndexes)

clusterIndexes = d_clusterIndexes.copy_to_host()

gpuEnd = datetime.now()
multiTime = multiEnd-multiStart
singleTime = gpuEnd-multiEnd

print("Single processing took: %s"%singleTime)


Choose the directory the cluster data is contained in.
Importing pickle file...
File imported
Seperating into clusters, outliers, and centers...


TypingError: Caused By:
Traceback (most recent call last):
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 463, in stage_nopython_frontend
    self.locals)
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 780, in type_inference_stage
    infer.propagate()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 565, in propagate
    raise errors[0]
TypingError: Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-8-1075e47721d4>", line 27

Failed at nopython (nopython frontend)
Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-8-1075e47721d4>", line 27

In [4]:
from numbapro import cuda, vectorize, guvectorize, check_cuda
from numbapro import void, uint8 , uint32, uint64, int32, int64, float32, float64, f8
import numpy as np

@cuda.autojit
def cu_add1(a, b, c):
    """This kernel function will be executed by a thread."""
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw

    if i > c.size:
        return

    c[i] = a[i] + b[i]
    
device = cuda.get_current_device()

n = 100

# Host memory
a = np.arange(n, dtype=np.float32)
b = np.arange(n, dtype=np.float32)

# Assign equivalent storage on device
da = cuda.to_device(a)
db = cuda.to_device(b)

# Assign storage on device for output
dc = cuda.device_array_like(a)

# Set up enough threads for kernel
tpb = device.WARP_SIZE
bpg = int(np.ceil(float(n)/tpb))
print 'Blocks per grid:', bpg
print 'Threads per block', tpb

# Launch kernel
cu_add1[bpg, tpb](da, db, dc)

# Transfer output from device to host
c = dc.copy_to_host()

print c

Blocks per grid: 4
Threads per block 32
[   0.    2.    4.    6.    8.   10.   12.   14.   16.   18.   20.   22.
   24.   26.   28.   30.   32.   34.   36.   38.   40.   42.   44.   46.
   48.   50.   52.   54.   56.   58.   60.   62.   64.   66.   68.   70.
   72.   74.   76.   78.   80.   82.   84.   86.   88.   90.   92.   94.
   96.   98.  100.  102.  104.  106.  108.  110.  112.  114.  116.  118.
  120.  122.  124.  126.  128.  130.  132.  134.  136.  138.  140.  142.
  144.  146.  148.  150.  152.  154.  156.  158.  160.  162.  164.  166.
  168.  170.  172.  174.  176.  178.  180.  182.  184.  186.  188.  190.
  192.  194.  196.  198.]


In [7]:
from numbapro import cuda
cuda.select_device(0)
import numpy as np

@cuda.autojit
def saxpy(a, b, c):
    # Determine our unique global thread ID, so we know which element to process
    tid = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x
    
    if ( tid < c.size ): # Make sure we don't do more work than we have data!
        c[tid] = 2 * a[tid] + b[tid]

@cuda.autojit
def clusterIndsCuda(clusterLabels,clusterIndexes):
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
    if i<=len(clusterLabels):
        if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels):
            clusterIndexes[i]=i
        else:
            clusterIndexes[i]=None
def main():
    N = len(clusterLabels)

    # Allocate host memory arrays
    a = np.array(clusterLabels)
    b = np.empty(N)

    # Initialize host memory
    a.fill(2)
    b.fill(None)

    # Allocate and copy GPU/device memory
    d_a = cuda.to_device(a)
    d_b = cuda.to_device(b)
    threads_per_block = 128
    number_of_blocks =N/128+1 ## FIXME: given the threads_per_block is set, determine how many blocks we need ##

    saxpy [ number_of_blocks, threads_per_block ] (d_a,d_b,d_c) ## FIXME: what variables do we pass? ##, N 

    ## FIXME: copy the vector c from the GPU back to the host ##
    d_c.copy_to_host(c)
    # Print out the first and last 5 values of c for a quality check
    print str(c[0:5])
    print str(c[-5:])
    
main() # Execute the program

N=len(clusterLabels)

d_clusterLabels = cuda.to_device(clusterLabels)
d_clusterIndexes=cuda.device_array_like(clusterLabels)

threads_per_block = 128
number_of_blocks =N/128+1

clusterIndsCuda[number_of_blocks,threads_per_block ] (d_clusterLabels,d_clusterIndexes)

clusterIndexes = d_clusterIndexes.copy_to_host()


[ 5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.]


In [1]:
import numbapro
numbapro.check_cuda()

numbapro:1: ImportWarning: The numbapro package is deprecated in favour of the accelerate package. Please update your code to use equivalent functions from accelerate.


------------------------------libraries detection-------------------------------
Finding cublas
	located at /home/dgiles/anaconda/lib/libcublas.so.7.0.28
	trying to open library...	ok
Finding cusparse
	located at /home/dgiles/anaconda/lib/libcusparse.so.7.0.28
	trying to open library...	ok
Finding cufft
	located at /home/dgiles/anaconda/lib/libcufft.so.7.0.35
	trying to open library...	ok
Finding curand
	located at /home/dgiles/anaconda/lib/libcurand.so.7.0.28
	trying to open library...	ok
Finding nvvm
	located at /home/dgiles/anaconda/lib/libnvvm.so.3.0.0
	trying to open library...	ok
	finding libdevice for compute_20...	ok
	finding libdevice for compute_30...	ok
	finding libdevice for compute_35...	ok
-------------------------------hardware detection-------------------------------
Found 1 CUDA devices
id 0            Quadro K2000                              [SUPPORTED]
                      compute capability: 3.0
                           pci device id: 0
                         

True