In [20]:
replace = raw_input('Clusters have already been produced, replace? (y/n) ')
n_ent = 1
while(not(replace=='y' or replace == 'n')):
    
    replace = raw_input("Response not recognized. Replace existing clusters? (y/n): ")
    if n_ent == 10:
        print("Too many invalid responses. Exiting program.")
        break
    n_ent += 1    
print(replace)

Clusters have already been produced, replace? (y/n) 1
Response not recognized. Replace existing clusters? (y/n): 2
Response not recognized. Replace existing clusters? (y/n): 3
Response not recognized. Replace existing clusters? (y/n): 4
Response not recognized. Replace existing clusters? (y/n): 5
Response not recognized. Replace existing clusters? (y/n): 6
Response not recognized. Replace existing clusters? (y/n): 7
Response not recognized. Replace existing clusters? (y/n): 8
Response not recognized. Replace existing clusters? (y/n): 9
Response not recognized. Replace existing clusters? (y/n): 10
Response not recognized. Replace existing clusters? (y/n): 11
Too many invalid responses. Exiting program.
11


In [25]:

identifier = raw_input('Enter the identifier of the data or type \'help\' for clarification: ')
if identifier == 'help':
    n_help = 1
    while(identifier == 'help'):
        if n_help == 2:
            print("\'help\' will be the assigned ID.")
            break
        print(
        '''
        This will look for a numpy array (.npy) with the identifier as a prefix.
        If you haven\'t made the numpy array with keplerml.py, abort this with ctrl-c and run
        keplerml.py. If you have run keplerml.py, input the identifier you chose.
        
        If you would like to assign \'help\' as the ID, enter it again when prompted,
        this help text will not appear again.

        For example, if you chose \'ex\', there will be a .npy file 
        called exdataByLightCurve.npy that will be read in.
        For the identifier you would input \'ex\'
        ''')
        identifier = raw_input('Enter the identifier of the data: ')
        
        n_help += 1

Enter the identifier of the data or type 'help' for clarification: help

        This will look for a numpy array (.npy) with the identifier as a prefix.
        If you haven't made the numpy array with keplerml.py, abort this with ctrl-c and run
        keplerml.py. If you have run keplerml.py, input the identifier you chose.
        
        If you would like to assign 'help' as the ID, enter it again when prompted.

        For example, if you chose 'ex', there will be a .npy file 
        called exdataByLightCurve.npy that will be read in.
        For the identifier you would input 'ex'
        
Enter the identifier of the data: help
'help' will be the assigned ID.


In [3]:
import sys,os
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk
from tkFileDialog import askopenfilename

Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
filename = askopenfilename() # show an "Open" dialog box and return the path to the selected file
pathtofile = os.path.dirname(filename)
print(filename)
print(pathtofile)

/home/dgiles/Documents/NESSF.zip
/home/dgiles/Documents


In [18]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=4, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)

print(indices)
print(distances[:,3])

[[0 1 2 3]
 [1 0 2 3]
 [2 1 0 3]
 [3 4 5 0]
 [4 3 5 0]
 [5 4 3 0]]
[ 2.82842712  3.60555128  5.          2.82842712  3.60555128  5.        ]


In [4]:
# Random index selection
import numpy as np
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk
from tkFileDialog import askopenfilename

print('Select the filelist')
Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
filelist = askopenfilename() # show an "Open" dialog box and return the path to the selected file

files = [line.strip() for line in open(filelist)]

randomLCs = np.random.choice(files, 1000, replace=False)

# test if Tabby star is included in the otherwise random set, insert if not
import fnmatch

tabbyCheck = fnmatch.filter(randomLCs, '*8462852*')
tabby = fnmatch.filter(files,'*8462852*')

if tabbyCheck==[]:
    randomLCs = np.delete(randomLCs,0)
    randomLCs = np.insert(randomLCs,0,tabby)
# output random filelist to randomizedFilelist
for i in range(len(randomLCs)):
    outputfile = open('randomizedFilelist','w')
    outputfile.write('%s\n'%randomLCs[i]) 

[54 25 26 61  9]


In [20]:
import fnmatch

files = ['a','b','c','d','e','heyo8462852.pie','f','g','h','i']
randomLCs = np.random.choice(files, 3, replace=False)
print(randomLCs)

tabbyCheck = fnmatch.filter(randomLCs, '*8462852*')
tabby = fnmatch.filter(files,'*8462852*')

if tabbyCheck==[]:
    randomLCs = np.delete(randomLCs,0)
    randomLCs = np.insert(randomLCs,0,tabby)
    
print(randomLCs)

['h' 'i' 'g']
Not Present
['heyo8462852.pie' 'i' 'g']


In [24]:
from datetime import datetime,time,timedelta
import os
from multiprocessing import Pool

thentime = datetime(2016,9,1,11,15,38)
times = [datetime(2016,9,1,11,16,38),datetime(2016,9,1,11,16,50),datetime(2016,9,1,11,17,50)]
#timedelta(days,seconds,microseconds,milliseconds,minutes,hours,weeks)
diff = timedelta(minutes=1)
identifier = 'test'

timediff = nowtime-thentime

def timeDifference(time):
    timediff=time-thentime
    nfile = str(time)[14:19]
    if time == datetime(2016,9,1,11,17,50):
        # inducing an error
        timediff = 'cat'
    if timediff>=diff:
        kml_log = identifier+'_kml_log'
        os.system('echo %s ... %s >> %s'%(nfile,timediff,kml_log))
    return timediff

p = Pool(3)
timediffs = p.map(timeDifference,times)
p.close()
p.terminate()
p.join()

print(timediffs)

TypeError: can't compare datetime.timedelta to str

In [74]:
import numpy as np
f = [3,2,3,-1,-2,-3]
#os.system('echo %s >> testoutput'%f)
files = [line.strip()[:] for line in open('testoutput')]
files.sort()
f = open('testsortedoutput','w')
for line in files:
    f.write(line[5:]+'\n')
f.close()
npfiles = np.loadtxt('testsortedoutput',delimiter=',')

def printthing():
    print(npfiles)
printthing()

[[ 1.  2.  3. -1. -2. -3.]
 [ 3.  2.  3. -1. -2. -3.]
 [ 2.  2.  3. -1. -2. -3.]]


In [86]:
hi = "Hi there "
hi5='%s'*5%(hi,hi,hi,hi,hi)
bye5=hi5.replace('Hi',"Bye")
print(hi5)
print(bye5)

Hi there Hi there Hi there Hi there Hi there 
Bye there Bye there Bye there Bye there Bye there 


In [21]:
import numpy as np
import os

files = [cat.strip() for cat in open('test_kml_log')]

print open('test_kml_log').readline()

line2



In [9]:
import Tkinter, Tkconstants, tkFileDialog

class TkFileDialogExample(Tkinter.Frame):

  def __init__(self, root):

    Tkinter.Frame.__init__(self, root)

    # options for buttons
    button_opt = {'fill': Tkconstants.BOTH, 'padx': 5, 'pady': 5}

    # define buttons
    Tkinter.Button(self, text='Choose Filelist', command=self.askopenfilename).pack(**button_opt)
    Tkinter.Button(self, text='Choose Output', command=self.asksaveasfilename).pack(**button_opt)
    Tkinter.Button(self, text='Choose Fits Files Directory', command=self.askdirectory).pack(**button_opt)

    # define options for opening or saving a file
    self.file_opt = options = {}
    options['initialdir'] = 'C:\\'
    options['parent'] = root
    options['title'] = 'This is a title'

    # This is only available on the Macintosh, and only when Navigation Services are installed.
    #options['message'] = 'message'

    # if you use the multiple file version of the module functions this option is set automatically.
    #options['multiple'] = 1

    # defining options for opening a directory
    self.dir_opt = options = {}
    options['initialdir'] = 'C:\\'
    options['mustexist'] = False
    options['parent'] = root
    options['title'] = 'This is a title'

  def askopenfilename(self):

    """Returns an opened file in read mode.
    This time the dialog just returns a filename and the file is opened by your own code.
    """

    # get filename
    filename = tkFileDialog.askopenfilename(**self.file_opt)

    # open file on your own
    if filename:
      return open(filename, 'r')

  def asksaveasfilename(self):

    """Returns an opened file in write mode.
    This time the dialog just returns a filename and the file is opened by your own code.
    """

    # get filename
    filename = tkFileDialog.asksaveasfilename(**self.file_opt)

    # open file on your own
    if filename:
      return open(filename, 'w')

  def askdirectory(self):

    """Returns a selected directoryname."""

    return tkFileDialog.askdirectory(**self.dir_opt)

if __name__=='__main__':
  root = Tkinter.Tk()
  TkFileDialogExample(root).pack()
  root.mainloop()


KeyboardInterrupt: 

In [16]:
import numpy as np

data = ['1','2','3']
data1 = [4,5,6,7]
data2 = [8,9,10,11,12,13]
files_array = []
files_array = data+data1+data2
print(files_array)

['1', '2', '3', 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [30]:
import cPickle as pickle
import numpy as np
import os
from multiprocessing import Pool

"""
IMPORTANT NOTE: It's possible to dump multiple times to the same output file. Loading that data will only load one
dump at a time, so it must be loaded as many times as it's dumped to access all data in a file.
"""

array = ['cat',1,2,3,1.234]
array2 = ['dog',4,5,6,6.543]
array3 = ['fish',1,10,100,1000.0001]
allarrays=[array,array2,array3]
# testing pickling


def picklestuff(stuff):
    if not os.path.isfile('testoutput'):
        open('testoutput','a').close()
    output = open('testoutput','a')
    pickle.dump(stuff,output)
    output.close()

if not os.path.isfile('testoutput'):
        open('testoutput','a').close()
output = open('testoutput','r+')
pickle.dump(array2,output)
pickle.dump(array3,output)
pickle.dump(array,output)
output.close()

# testing unpickling
testinput = open('testoutput','r+')
"""
pik=pickle.load(testinput)
pik2=pickle.load(testinput)
testinput.close()
"""
pik=[]
while True:
    try:
        o = pickle.load(testinput)
    except EOFError:
        break
    else:
        pik.append(o)
testinput.close()

print(pik)
print('')
pik.sort()

# Testing if it all pickles as one array now.
output=open('testsortedoutput','r+')
pickle.dump(pik,output)
output.close()

testinput = open('testsortedoutput','r')
newpik = pickle.load(testinput)
testinput.close()
print(newpik)
# it does pickle as one array now, good.
animals = [newpik[i][0] for i in range(len(newpik))]
print(animals)

[['dog', 4, 5, 6, 6.543], ['fish', 1, 10, 100, 1000.0001], ['cat', 1, 2, 3, 1.234]]

[['cat', 1, 2, 3, 1.234], ['dog', 4, 5, 6, 6.543], ['fish', 1, 10, 100, 1000.0001]]
['cat', 'dog', 'fish']


In [1]:
import sys
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk

from tkFileDialog import askopenfilename,askdirectory


Tk().withdraw() 
output = askopenfilename()

if output:
    outputfile = open(output,'r+') # show an "Open" dialog box and return the path to the selected file
    print("woo")
    outputfile.close()
else:
    print("boo")



boo


In [3]:
import numpy as np
np.set_printoptions(threshold='nan')
import os
import sys
import cPickle as pickle
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk

from tkFileDialog import askopenfilename,askdirectory
output = askopenfilename() # locate the pickle file with the relevant data

if output:
    pathtofile = os.path.dirname(output)
    outputfile = open(output,'r+') # show an "Open" dialog box and return the path to the selected file
    outputdata = []
    while True:
        try:
            o = pickle.load(outputfile)
        except EOFError:
            break
        else:
            outputdata.append(o)
    outputfile.close()

    files = [outputdata[i][0] for i in range(len(outputdata))]
    data = np.array([outputdata[i][1:] for i in range(len(outputdata))])
    print(files[0])
    print(data[0])

In [41]:
#run cell above before this one
weirddata = [i for i in data if np.isnan(i).any()]
weirddatainds = [i for i in range(len(data)) if np.isnan(data[i]).any()]
print(weirddatainds)

[46863, 50739, 77707, 92257, 159088]


In [46]:
ind=4
print(files[weirddatainds[ind]])
print(weirddata[ind])

kplr011495654-2010174085026_llc.fits
[ -9.93052528e-04   9.84048903e-01  -2.68960282e-01   1.53136747e-02
   1.25754356e-01   1.23748437e-01   0.00000000e+00   0.00000000e+00
   0.00000000e+00   2.06300000e+03  -1.25817058e+00   1.10004127e-01
   1.80803572e-03   2.40955732e-02  -1.63906125e-02   1.13105677e-02
  -9.22863996e-03  -1.22559421e+00   1.00000000e+00   2.08192773e-03
   1.75979106e-01   3.62931098e-05   1.40091913e-04   1.03473570e-02
   1.48490393e-01   5.00000000e+00   9.00000000e+00   1.70000000e+01
   1.70000000e+01   1.52735526e+00   3.00000000e+00   1.05000000e+02
   2.00000000e+00   5.00000000e+00              nan   1.43846328e-04
   0.00000000e+00   0.00000000e+00   6.92923236e+01   4.33051726e-03
   8.66103452e-03   9.16041195e-01   3.79079232e-01   3.85223977e-01
   0.00000000e+00   1.72380316e-01   4.03968186e-01   6.27886671e-01
   8.24295422e-01   9.49554305e-01   1.55821562e-01   4.11052753e-01
   8.83818335e-01   9.99997513e-01   9.47999114e-04   4.55169903e-

In [11]:
import numpy as np
ints = [0,2,4]
otherints = [1,3,5]
array = np.array(['a','b','c','d','e','f'])
newarray = []
newarray.append(array[ints])
newarray.append(array[otherints])
print(newarray[0])
print(array[ints+otherints])

['a' 'c' 'e']
['a' 'c' 'e' 'b' 'd' 'f']


In [25]:
a = np.array([1,1,1,1,1,1,None,2,2,2,2,3,None])
a = [i for i in a if i !=None]
print(a)

[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3]


In [6]:
from datetime import datetime,time,timedelta
import random
import numpy as np
from multiprocessing import Pool,cpu_count
import sys
import os
import cPickle as pickle
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk
    
from tkFileDialog import askopenfilename,askdirectory

root = Tk.Tk()
root.wm_title("Scatter")

def reorganizeArray(X): 
    # This is just a transposition, could be accomplished by making X an np.array then transposing via X.T if prefered
    # TODO: Time the difference with large datasets (100,000+)
    return [[X[i][j] for i in range(len(X))] for j in range(len(X[0]))]

def outlierInds(i):
    #framework for multiprocessing to be implemented
    clusterLabels=np.load('labels_temp.npy')
    if clusterLabels[i] == max(clusterLabels):
        return i
def centerInds(i):
    clusterLabels=np.load('labels_temp.npy')
    if clusterLabels[i] == 0:
        return i
def clusterInds(i):
    clusterLabels=np.load('labels_temp.npy')
    if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels):
        return i

Tk.Tk.withdraw(root)
print("Choose the directory the cluster data is contained in.")
pathtofile = askopenfilename() # Choose the cluster file
openclusterfile = open(pathtofile,'r+')
print("Importing pickle file...")
clusterfile = pickle.load(openclusterfile)
print("File imported")
openclusterfile.close()
files = np.array(clusterfile[0])
clusterLabels = np.array(clusterfile[1])
data = np.array(clusterfile[2])

clusterIndices = []
outlierIndices = []
centerIndices = []
print("Seperating into clusters, outliers, and centers...")

multiStart = datetime.now()
np.save('labels_temp.npy',clusterLabels)
numcpus = cpu_count()
if numcpus > 2:
    # Leave 1 cpus open for system tasks.
    usecpus = numcpus-2
else:
    usecpus = 1
p = Pool(usecpus)
clusterIndices = p.map(clusterInds,range(len(files)))
p.close()
p.terminate()
p.join()
os.remove('labels_temp.npy')
multiEnd = datetime.now()
clusterIndices = [i for i in range(len(files)) if clusterLabels[i]!=0 and clusterLabels[i]<max(clusterLabels)]
arrayEnd = datetime.now()
multiTime = multiEnd-multiStart
singleTime = arrayEnd-multiEnd

print("Multi processing took: %s"%multiTime)
print("Single processing took: %s"%singleTime)
"""print("Seperated, choosing random cluster points to display...")
# I don't think anyone has a real interest in seeing hundreds of thousands of 'normal' points, choosing a random sampling
# TODO: use density estimation to display all data
randomClusterIndices = np.random.choice(clusterIndices,1000,replace=False)
print("Reforming data arrays...")
inds = np.append(randomClusterIndices,outlierIndices)
inds = np.append(inds,centerIndices)
inds = [i for i in inds if i!=None]
files = files[inds]
clusterLabels = clusterLabels[inds]
data = data[inds]
plotArray = [files,clusterLabels,data]
print("Plot in next cell.")"""

Choose the directory the cluster data is contained in.
Importing pickle file...
File imported
Seperating into clusters, outliers, and centers...


TypingError: Caused By:
Traceback (most recent call last):
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 463, in stage_nopython_frontend
    self.locals)
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 780, in type_inference_stage
    infer.propagate()
  File "/home/dgiles/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 565, in propagate
    raise errors[0]
TypingError: Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-6-ffcac364267d>", line 37

Failed at nopython (nopython frontend)
Invalid usage of Function(<built-in function max>) with parameters (array(int64, 1d, A))
 * parameterized
File "<ipython-input-6-ffcac364267d>", line 37

In [66]:
from datetime import datetime,time,timedelta
import random
import numpy as np
from multiprocessing import Pool,cpu_count
import sys
import os
import cPickle as pickle
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk
    
from tkFileDialog import askopenfilename,askdirectory

from numbapro import cuda

@cuda.autojit
def clusterIndsCuda(clusterLabels,clusterIndexes):
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
    if i<=len(clusterLabels):
        if clusterLabels[i]!=0 and clusterLabels[i]<outs:
            clusterIndexes[i]=int(i)
        else:
            clusterIndexes[i]=N+1
            return

            
multiEnd = datetime.now()

### Start Cuda GPU Stuff ###
outs=max(clusterLabels)
N=len(clusterLabels)
d_clusterLabels = cuda.to_device(clusterLabels)

clusterIndexes = np.empty(N)
d_clusterIndexes=cuda.to_device(clusterIndexes)
N=len(clusterLabels)
threads_per_block = 128
number_of_blocks =N/128+1

clusterIndsCuda[number_of_blocks,threads_per_block ] (d_clusterLabels,d_clusterIndexes)

clusterIndexes = d_clusterIndexes.copy_to_host()
clusterIndexes = [int(clusterIndexes[i]) for i in range(len(clusterIndexes)) if clusterIndexes[i]<(N+1)]
gpuEnd = datetime.now()
multiTime = multiEnd-multiStart
singleTime = gpuEnd-multiEnd

print("Single processing took: %s"%singleTime)
print clusterIndexes[100:1000]

Single processing took: 0:00:00.315229
[101, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 

In [4]:
from numbapro import cuda, vectorize, guvectorize, check_cuda
from numbapro import void, uint8 , uint32, uint64, int32, int64, float32, float64, f8
import numpy as np

@cuda.autojit
def cu_add1(a, b, c):
    """This kernel function will be executed by a thread."""
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw

    if i > c.size:
        return

    c[i] = a[i] + b[i]
    
device = cuda.get_current_device()

n = 100

# Host memory
a = np.arange(n, dtype=np.float32)
b = np.arange(n, dtype=np.float32)

# Assign equivalent storage on device
da = cuda.to_device(a)
db = cuda.to_device(b)

# Assign storage on device for output
dc = cuda.device_array_like(a)

# Set up enough threads for kernel
tpb = device.WARP_SIZE
bpg = int(np.ceil(float(n)/tpb))
print 'Blocks per grid:', bpg
print 'Threads per block', tpb

# Launch kernel
cu_add1[bpg, tpb](da, db, dc)

# Transfer output from device to host
c = dc.copy_to_host()

print c

Blocks per grid: 4
Threads per block 32
[   0.    2.    4.    6.    8.   10.   12.   14.   16.   18.   20.   22.
   24.   26.   28.   30.   32.   34.   36.   38.   40.   42.   44.   46.
   48.   50.   52.   54.   56.   58.   60.   62.   64.   66.   68.   70.
   72.   74.   76.   78.   80.   82.   84.   86.   88.   90.   92.   94.
   96.   98.  100.  102.  104.  106.  108.  110.  112.  114.  116.  118.
  120.  122.  124.  126.  128.  130.  132.  134.  136.  138.  140.  142.
  144.  146.  148.  150.  152.  154.  156.  158.  160.  162.  164.  166.
  168.  170.  172.  174.  176.  178.  180.  182.  184.  186.  188.  190.
  192.  194.  196.  198.]


In [51]:
from numbapro import cuda
cuda.select_device(0)
import numpy as np

@cuda.autojit
def saxpy(a, b, c):
    # Determine our unique global thread ID, so we know which element to process
    tid = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x
    
    if ( tid < c.size ): # Make sure we don't do more work than we have data!
        c[tid] = 2 * a[tid] + b[tid]

@cuda.autojit
def clusterIndsCuda(cows,clusterIndexes):
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
        
    if i<=len(cows):
        if cows[i]!=0:
            if cows[i]<6:
                clusterIndexes[i]=i
    else:
        return
    #    clusterIndexes[i]=N+1
    
def main():
    N = len(clusterLabels)

    # Allocate host memory arrays
    a = np.array(clusterLabels)
    b = np.empty(N)

    # Initialize host memory
    a.fill(2)
    b.fill(None)

    # Allocate and copy GPU/device memory
    d_a = cuda.to_device(a)
    d_b = cuda.to_device(b)
    threads_per_block = 128
    number_of_blocks =N/128+1 ## FIXME: given the threads_per_block is set, determine how many blocks we need ##

    clusterIndsCuda [ number_of_blocks, threads_per_block ] (d_a,d_b) ## FIXME: what variables do we pass? ##, N 

    ## FIXME: copy the vector c from the GPU back to the host ##
    d_b.copy_to_host(b)
    print b[0:10]
    print b[-5:]
    print N
    print len(b)
    print clusterLabels[0:100]
main() # Execute the program

N=len(clusterLabels)

"""d_clusterLabels = cuda.to_device(clusterLabels)
d_clusterIndexes=cuda.device_array_like(clusterLabels)

threads_per_block = 128
number_of_blocks =N/128+1

clusterIndsCuda[number_of_blocks,threads_per_block ](d_clusterLabels,d_clusterIndexes)

clusterIndexes = d_clusterIndexes.copy_to_host()"""


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 166263.  166264.  166265.  166266.  166267.]
166268
166268
[4 2 4 4 6 1 4 6 6 4 4 2 7 1 1 6 1 1 1 3 1 4 1 3 1 2 4 3 4 1 1 1 1 2 1 1 1
 6 6 5 1 1 1 3 5 1 4 1 5 5 1 4 4 2 4 4 1 4 1 1 6 1 6 1 1 1 1 4 2 4 1 4 6 6
 5 6 1 1 6 1 1 2 6 3 1 1 1 6 1 3 1 1 1 1 1 4 1 1 4 1]


'd_clusterLabels = cuda.to_device(clusterLabels)\nd_clusterIndexes=cuda.device_array_like(clusterLabels)\n\nthreads_per_block = 128\nnumber_of_blocks =N/128+1\n\nclusterIndsCuda[number_of_blocks,threads_per_block ](d_clusterLabels,d_clusterIndexes)\n\nclusterIndexes = d_clusterIndexes.copy_to_host()'

In [1]:
import numbapro
numbapro.check_cuda()

numbapro:1: ImportWarning: The numbapro package is deprecated in favour of the accelerate package. Please update your code to use equivalent functions from accelerate.


------------------------------libraries detection-------------------------------
Finding cublas
	located at /home/dgiles/anaconda/lib/libcublas.so.7.0.28
	trying to open library...	ok
Finding cusparse
	located at /home/dgiles/anaconda/lib/libcusparse.so.7.0.28
	trying to open library...	ok
Finding cufft
	located at /home/dgiles/anaconda/lib/libcufft.so.7.0.35
	trying to open library...	ok
Finding curand
	located at /home/dgiles/anaconda/lib/libcurand.so.7.0.28
	trying to open library...	ok
Finding nvvm
	located at /home/dgiles/anaconda/lib/libnvvm.so.3.0.0
	trying to open library...	ok
	finding libdevice for compute_20...	ok
	finding libdevice for compute_30...	ok
	finding libdevice for compute_35...	ok
-------------------------------hardware detection-------------------------------
Found 1 CUDA devices
id 0            Quadro K2000                              [SUPPORTED]
                      compute capability: 3.0
                           pci device id: 0
                         

True

In [ ]:
from datetime import datetime,timedelta

# L.M. Walkowicz, D.K. Giles
# Rewrite of Revant's feature calculations, plus additional functions for vetting outliers
import os
import random
import numpy as np
np.set_printoptions(threshold='nan')
import scipy as sp
from scipy import stats
import pyfits
import math
#import pylab as pl
#import matplotlib.pyplot as plt
import heapq
from operator import xor
import scipy.signal
from numpy import float64
#import astroML.time_series
#import astroML_addons.periodogram
#import cython
from sklearn.decomposition import PCA
#from sklearn.cluster import KMeans
#from sklearn.cluster import DBSCAN,Ward
from numpy.random import RandomState
#rng = RandomState(42)
import itertools
import commands
# import utils
#from astropy.io import fits
from multiprocessing import Pool,cpu_count
#from mpl_toolkits.mplot3d import Axes3D
#from matplotlib.widgets import RadioButtons
import sys
import cPickle as pickle
from numbapro import cuda
if sys.version_info[0] < 3:
    from Tkinter import Tk
else:
    from tkinter import Tk

from tkFileDialog import askopenfilename,askdirectory


def readLightcurves(file):
    lcf = fits.open(file)
    lc = lcf.data
    t = lc.field('TIME')
    f = lc.field('PDCSAP_FLUX')
    err = lc.field('PDCSAP_FLUX_ERR')

    f = f[np.isfinite(t)]
    t = t[np.isfinite(t)]
    t = t[np.isfinite(f)]
    f = f[np.isfinite(f)]

    nf = f / np.median(f)
    del lc
    del lcf.data
    lcf.close()
    return t,nf,err

@cuda.autojit
def fcalc(t,nf,err,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,\
          f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,\
          f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,\
          f31,f32,f33,f34,f35,f36,f37,f38,f39,f40,\
          f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,\
          f51,f52,f53,f54,f55,f56,f57,f58,f59,f60):
    
    bx = cuda.blockIdx.x # which block in the grid?
    bw = cuda.blockDim.x # what is the size of a block?
    tx = cuda.threadIdx.x # unique thread ID within a blcok
    i = tx + bx * bw
    
    t=t[i]
    nf = nf[i]
    err=err[i]

    # t = time
    # err = error
    # nf = normalized flux. Same as mf but offset by 1 to center at 0?

    """
    longtermtrend = np.polyfit(t, nf, 1)[0] # Feature 1 (Abbr. F1) overall slope
    yoff = np.polyfit(t, nf, 1)[1] # Not a feature? y-intercept of linear fit
    meanmedrat = np.mean(nf) / np.median(nf) # F2
    skews = scipy.stats.skew(nf) # F3
    varss = np.var(nf) # F4
    coeffvar = np.std(nf)/np.mean(nf) #F5
    stds = np.std(nf) #F6
    
    corrnf = nf - longtermtrend*t - yoff #this removes any linear slope to lc so you can look at just troughs - is this a sign err tho?
    # D: I don't think there's a sign error

    # Features 7 to 10
    numoutliers, numposoutliers, numnegoutliers, numout1s = calc_outliers_pts(t, nf)

    kurt = scipy.stats.kurtosis(nf)

    mad = np.median([abs(nf[j]-np.median(nf)) for j in range(len(nf))])

    # slopes array contains features 13-30
    #slopes, corrslopes, secder, slopes_array = calc_slopes(t, nf, corrnf) 
    slopes, corrslopes, secder, maxslope,minslope ,meanpslope,meannslope,g_asymm,\
    rough_g_asymm,diff_asymm,skewslope,varabsslope,\
    varslope,meanabsslope,absmeansecder,num_pspikes,\
    num_nspikes ,num_psdspikes,num_nsdspikes,stdratio,pstrend=calc_slopes(t, nf, corrnf) 

    # Checks if the flux crosses the zero line.
    zcrossind= [j for j in range(len(nf)-1) if corrnf[j]*corrnf[j+1]<0]
    num_zcross = len(zcrossind) #F31

    plusminus=[j for j in range(1,len(slopes)) if (slopes[j]<0)&(slopes[j-1]>0)]
    num_pm = len(plusminus)

    # peak to peak array contains features 33 - 42
    peaktopeak_array, naivemax, naivemins = calc_maxmin_periodics(t, nf, err)

    len_nmax,len_nmin,mautocorrcoef,ptpslopes,\
    periodicity,periodicityr,naiveperiod,maxvars,\
    maxvarsr,oeratio,naivemax,naivemins=calc_maxmin_periodics(t, nf, err)

    # amp here is actually amp_2 in revantese
    # 2x the amplitude (peak-to-peak really), the 1st percentile will be negative, so it's really adding magnitudes
    amp = np.percentile(nf,99)-np.percentile(nf,1) #F43
    normamp = amp / np.mean(nf) #this should prob go, since flux is norm'd #F44

    # ratio of points within 10% of middle to total number of points 
    mbp = len([nf[j] for j in range(len(nf)) if (nf[j] < (np.median(nf) + 0.1*amp)) & (nf[j] > (np.median(nf)-0.1*amp))]) / len(nf) #F45

    f595 = np.percentile(nf,95)-np.percentile(nf,5)
    f1090 =np.percentile(nf,90)-np.percentile(nf,10)
    f1782 =np.percentile(nf, 82)-np.percentile(nf, 17)
    f2575 =np.percentile(nf, 75)-np.percentile(nf, 25)
    f3267 =np.percentile(nf, 67)-np.percentile(nf, 32)
    f4060 =np.percentile(nf, 60)-np.percentile(nf, 40)
    mid20 =f4060/f595 #F46
    mid35 =f3267/f595 #F47
    mid50 =f2575/f595 #F48
    mid65 =f1782/f595 #F49
    mid80 =f1090/f595 #F50 

    percentamp = max([(nf[j]-np.median(nf)) / np.median(nf) for j in range(len(nf))]) #F51
    magratio = (max(nf)-np.median(nf)) / amp #F52

    #autopdc=[nf[j+1] for j in range(len(nf)-1)] = nf[1:]
    autocorrcoef = np.corrcoef(nf[:-1], nf[1:])[0][1] #F54
    #autocovs = np.cov(nf[:-1], nf[1:])[0][1] # not used for anything...

    #sautopdc=[slopes[j+1] for j in range(len(slopes)-1)] = slopes[1:]

    sautocorrcoef = np.corrcoef(slopes[:-1], slopes[1:])[0][1] #F55
    #sautocovs = np.cov(slopes[:-1:],slopes[1:])[0][1] # not used for anything...

    flatness = [np.mean(slopes[max(0,j-6):min(j-1, len(slopes)-1):1])- np.mean(slopes[max(0,j):min(j+4, len(slopes)-1):1]) for j in range(len(slopes)) if nf[j] in naivemax]

    flatmean = np.nansum(flatness)/len(flatness) #F55

    # trying flatness w slopes and nf rather than "corr" vals, despite orig def in RN's program
    tflatness = [-np.mean(slopes[max(0,j-6):min(j-1, len(slopes)-1):1])+ np.mean(slopes[max(0,j):min(j+4, len(slopes)-1):1]) for j in range(len(slopes)) if nf[j] in naivemins] 
    # tflatness for mins, flatness for maxes
    tflatmean = np.nansum(tflatness) / len(tflatness) #F56

    roundness=[np.mean(secder[max(0,j-6):min(j-1, len(secder)-1):1]) + np.mean(secder[max(0,j+1):min(j+6, len(secder)-1):1]) for j in range(len(secder)) if nf[j+1] in naivemax]

    roundmean = np.nansum(roundness) / len(roundness) #F57

    troundness = [np.mean(secder[max(0,j-6):min(j-1, len(secder)-1):1]) + np.mean(secder[max(0,j+1):min(j+6, len(secder)-1):1]) for j in range(len(secder)) if nf[j+1] in naivemins]

    troundmean = np.nansum(troundness)/len(troundness) #F58
    roundrat = roundmean / troundmean #F59

    flatrat = flatmean / tflatmean #F60
    """
    
    #f1[i],f2[i],f3[i],f4[i],f5[i],f6[i],f7[i],f8[i],f9[i],f10[i]=longtermtrend, meanmedrat, skews, varss, coeffvar, stds, numoutliers, numnegoutliers, numposoutliers, numout1s
    #f11[i],f12[i],f13[i],f14[i],f15[i],f16[i],f17[i],f18[i],f19[i],f20[i]=kurt, mad, maxslope, minslope, meanpslope, meannslope, g_asymm, rough_g_asymm, diff_asymm, skewslope
    #f21[i],f22[i],f23[i],f24[i],f25[i],f26[i],f27[i],f28[i],f29[i],f30[i]=varabsslope, varslope, meanabsslope, absmeansecder, num_pspikes, num_nspikes, num_psdspikes, num_nsdspikes,stdratio, pstrend
    #f31[i],f32[i],f33[i],f34[i],f35[i],f36[i],f37[i],f38[i],f39[i],f40[i]=num_zcross, num_pm, len_nmax, len_nmin, mautocorrcoef, ptpslopes, periodicity, periodicityr, naiveperiod, maxvars
    #f41[i],f42[i],f43[i],f44[i],f45[i],f46[i],f47[i],f48[i],f49[i],f50[i]=maxvarsr, oeratio, amp, normamp,mbp, mid20, mid35, mid50, mid65, mid80
    #f51[i],f52[i],f53[i],f54[i],f55[i],f56[i],f57[i],f58[i],f59[i],f60[i]=percentamp, magratio, sautocorrcoef, autocorrcoef, flatmean, tflatmean, roundmean, troundmean, roundrat, flatrat
    f1[i],f2[i],f3[i],f4[i],f5[i],f6[i],f7[i],f8[i],f9[i],f10[i]=i,i,i,i,i,i,i,i,i,i
    f11[i],f12[i],f13[i],f14[i],f15[i],f16[i],f17[i],f18[i],f19[i],f20[i]=i,i,i,i,i,i,i,i,i,i
    f21[i],f22[i],f23[i],f24[i],f25[i],f26[i],f27[i],f28[i],f29[i],f30[i]=i,i,i,i,i,i,i,i,i,i
    f31[i],f32[i],f33[i],f34[i],f35[i],f36[i],f37[i],f38[i],f39[i],f40[i]=i,i,i,i,i,i,i,i,i,i
    f41[i],f42[i],f43[i],f44[i],f45[i],f46[i],f47[i],f48[i],f49[i],f50[i]=i,i,i,i,i,i,i,i,i,i
    f51[i],f52[i],f53[i],f54[i],f55[i],f56[i],f57[i],f58[i],f59[i],f60[i]=i,i,i,i,i,i,i,i,i,i

def readLightCurves(file):
    lc = pyfits.getdata(files[i],memmap=False)
    t = lc.field('TIME')
    f = lc.field('PDCSAP_FLUX')
    err = lc.field('PDCSAP_FLUX_ERR')
    del lc
    f = f[np.isfinite(t)]
    t = t[np.isfinite(t)]
    t = t[np.isfinite(f)]
    f = f[np.isfinite(f)]

    nf = f / np.median(f)
    
    return t, nf, err

    

    
def feature_calc(read_curves):
    print("Importing filelist...")
    files = np.array([fitsDir+'/'+line.strip() for line in open(filelist)])
    print("")
    print("Calculating features...")
    t=read_curves[0]
    nf=read_curves[1]
    err=read_curves[2]
        
    out = np.empty(len(files))
    d_t=cuda.to_device(t)
    d_nf=cuda.to_device(nf)
    d_err=cuda.to_device(err)

    d_f1,d_f2,d_f3,d_f4,d_f5,d_f6,d_f7,d_f8,d_f9,d_f10 = cuda.to_device(out),cuda.to_device(out),\
                                                            cuda.to_device(out),cuda.to_device(out),\
                                                            cuda.to_device(out),cuda.to_device(out),\
                                                            cuda.to_device(out),cuda.to_device(out),\
                                                            cuda.to_device(out),cuda.to_device(out)
    d_f11,d_f12,d_f13,d_f14,d_f15,d_f16,d_f17,d_f18,d_f19,d_f20 = cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out)
    d_f21,d_f22,d_f23,d_f24,d_f25,d_f26,d_f27,d_f28,d_f29,d_f30 = cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out)
    d_f31,d_f32,d_f33,d_f34,d_f35,d_f36,d_f37,d_f38,d_f39,d_f40 = cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out)
    d_f41,d_f42,d_f43,d_f44,d_f45,d_f46,d_f47,d_f48,d_f49,d_f50 = cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out)    
    d_f51,d_f52,d_f53,d_f54,d_f55,d_f56,d_f57,d_f58,d_f59,d_f60 = cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out),\
                                                                cuda.to_device(out),cuda.to_device(out)
    
    threads_per_block = 128
    number_of_blocks = len(files)/128+1
    
    fcalc[number_of_blocks,threads_per_block](d_t,d_nf,d_err,d_f1,d_f2,d_f3,d_f4,d_f5,d_f6,d_f7,d_f8,d_f9,d_f10,\
                                              d_f11,d_f12,d_f13,d_f14,d_f15,d_f16,d_f17,d_f18,d_f19,d_f20,\
                                              d_f21,d_f22,d_f23,d_f24,d_f25,d_f26,d_f27,d_f28,d_f29,d_f30,\
                                              d_f31,d_f32,d_f33,d_f34,d_f35,d_f36,d_f37,d_f38,d_f39,d_f40,\
                                              d_f41,d_f42,d_f43,d_f44,d_f45,d_f46,d_f47,d_f48,d_f49,d_f50,\
                                              d_f51,d_f52,d_f53,d_f54,d_f55,d_f56,d_f57,d_f58,d_f59,d_f60)
    
    f1,f2,f3,f4,f5,f6,f7,f8,f9,f10 = d_f1.copy_to_host(),d_f2.copy_to_host(),d_f3.copy_to_host(),\
                                                        d_f4.copy_to_host(),d_f5.copy_to_host(),d_f6.copy_to_host(),\
                                                        d_f7.copy_to_host(),d_f8.copy_to_host(),d_f9.copy_to_host(),\
                                                        d_f10.copy_to_host()
    f11,f12,f13,f14,f15,f16,f17,f18,f19,f20 = d_f11.copy_to_host(),d_f12.copy_to_host(),d_f13.copy_to_host(),\
                                                        d_f14.copy_to_host(),d_f15.copy_to_host(),d_f16.copy_to_host(),\
                                                        d_f17.copy_to_host(),d_f18.copy_to_host(),d_f19.copy_to_host(),\
                                                        d_f20.copy_to_host()
    f21,f22,f23,f24,f25,f26,f27,f28,f29,f30 = d_f21.copy_to_host(),d_f22.copy_to_host(),d_f23.copy_to_host(),\
                                                        d_f24.copy_to_host(),d_f25.copy_to_host(),d_f26.copy_to_host(),\
                                                        d_f27.copy_to_host(),d_f28.copy_to_host(),d_f29.copy_to_host(),\
                                                        d_f30.copy_to_host()
    f31,f32,f33,f34,f35,f36,f37,f38,f39,f40 = d_f31.copy_to_host(),d_f32.copy_to_host(),d_f33.copy_to_host(),\
                                                        d_f34.copy_to_host(),d_f35.copy_to_host(),d_f36.copy_to_host(),\
                                                        d_f37.copy_to_host(),d_f38.copy_to_host(),d_f39.copy_to_host(),\
                                                        d_f40.copy_to_host()
    f41,f42,f43,f44,f45,f46,f47,f48,f49,f50 = d_f41.copy_to_host(),d_f42.copy_to_host(),d_f43.copy_to_host(),\
                                                        d_f44.copy_to_host(),d_f45.copy_to_host(),d_f46.copy_to_host(),\
                                                        d_f47.copy_to_host(),d_f48.copy_to_host(),d_f49.copy_to_host(),\
                                                        d_f50.copy_to_host()   
    f51,f52,f53,f54,f55,f56,f57,f58,f59,f60 = d_f51.copy_to_host(),d_f52.copy_to_host(),d_f53.copy_to_host(),\
                                                        d_f54.copy_to_host(),d_f55.copy_to_host(),d_f56.copy_to_host(),\
                                                        d_f57.copy_to_host(),d_f58.copy_to_host(),d_f59.copy_to_host(),\
                                                        d_f60.copy_to_host()
    output = []
    for i in range(len(files)):
        output.append([f1[i],f2[i],f3[i],f4[i],f5[i],f6[i],f7[i],f8[i],f9[i],\
                f10[i],f11[i],f12[i],f13[i],f14[i],f15[i],f16[i],f17[i],f18[i],f19[i],\
                f20[i],f21[i],f22[i],f23[i],f24[i],f25[i],f26[i],f27[i],f28[i],f29[i],\
                f30[i],f31[i],f32[i],f33[i],f34[i],f35[i],f36[i],f37[i],f38[i],f39[i],\
                f40[i],f41[i],f42[i],f43[i],f44[i],f45[i],f46[i],f47[i],f48[i],f49[i],\
                f50[i],f51[i],f52[i],f53[i],f54[i],f55[i],f56[i],f57[i],f58[i],f59[i],f60[i]])
    if not os.path.isfile(identifier+'_output'):
        open(identifier+'_output','a').close()
    id_output=open(identifier+'_output','a')
    pickle.dump(output,id_output)
    id_output.close()
    
    print("Features Calculated")
    #return data

# 'data' contains the output as arrays of all the features for each lightcurve, necessary for clustering
#data = feature_calc(filelist)


"""
Run the program on the filelist chosen.
"""

print('Select the filelist')
Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
filelist = askopenfilename() # show an "Open" dialog box and return the path to the selected file
if filelist:
    print('Select the fits files location (must all be in one directory)')
    Tk().withdraw() # we don't want a full GUI, so keep the root window from appearing
    fitsDir = askdirectory() # show an "Open" dialog box and return the path to the selected file
    if fitsDir:
        identifier=str(raw_input('Choose a unique identifier: '))
        outputfile = identifier+'_output'
        while os.path.isfile(outputfile):
            replace = raw_input('Output exists for identifier, replace? ("y" to replace, any other input repeats the prompt) ')
            if replace == 'y':
                os.system('rm %s'%outputfile)
            elif replace == 'add':
                break
            else:
                identifier=str(raw_input('Choose a unique identifier: '))
                outputfile = identifier+'_output'
        startTime = datetime.now()
        
        if __name__ == '__main__':
            numcpus = cpu_count()
            if numcpus > 1:
                # Leave 2 cpus open for system tasks.
                usecpus = numcpus-2
            else:
                usecpus = 1

            p = Pool(usecpus)
            #data = p.map(fcalc,files)
            read_curves = p.map(readLightCurves,files)
            p.close()
            p.terminate()
        p.join()
        
        feature_calc(read_curves)
        endTime = datetime.now()
        totalTime = endTime-startTime
        print("Done, took %s"%totalTime)


Select the filelist
Select the fits files location (must all be in one directory)
Choose a unique identifier: fdas
Importing filelist...

Calculating features...


ValueError: Attempted relative import in non-package